### ISSUE TITLE
Specifying meaningful story names

### ISSUE THREAD

**Issue by njenia** [jondot/storybook-cartesian#1]
Currently we can specify the name template for a story.
Then we get story names like `"Click me" #F4F3F4 / #F1A233`.
It would be cool if you could give each value of a prop a more semantic name and get names like `regular text | dark color / light color`.
One possible implementation is to have an optional format for the props in the seed function:
```
.add(() => ({
  colors: [
            {storyDesc: 'dark colors', propValue: { bg: '#FF5630', fg: '#FFBDAD' }}, 
            { bg: '#4C9AFF', fg: '#B3D4FF' }
        ],
        text: ['Click Me', {storyDesc: 'empty text', propValue: ''}, '你好']
}))
```
But then the title renderer will be more complex as the user will need to reference these new format fields explicitly, to keep the title flexible.
wdyt?

**Comment by jondot** [comment]
see https://github.com/jondot/storybook-cartesian#beautiful-names-for-variants
